Works section project
karam084/My-Portfolio pull request #2
Opened 2021-09-23 23:28 UTC by karam084

- Create a class (flex-botu).
- Create a class (resume).
- Create .flex-botu style
- Create .resume style.

2021-09-24 04:37 UTC, mke2111 requested changes
### Hey @karam084, 

**This is a great project you have going on, well-done lad**. 

   
**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

## Required Changes ♻️
_Check the inline comments under the review for sections to improve._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-24 04:42 UTC, mke2111 commented on index.html
> +         </div>
- [ ] For this milestone, you are required to add the complete sections of projects and about me. Currently, from the template you have chosen, there should be 4 projects listed (you are having one project listed) and the about section comes after the projects section (your about section is coming before the projects section).
![Screenshot_2021-09-24 My Portfolio](https://user-images.githubusercontent.com/65501535/134619323-0998a6b5-d985-4fe5-a941-c46903b3a256.png)

- Fix the order of the sections just like they are listed in the figma design.

2021-09-24 04:46 UTC, mke2111 commented on index.html
> +         </div>
- [ ] This should be a `button` tag

2021-09-24 04:47 UTC, mke2111 commented on index.html
> +                 <li>Tonic</li>
- [ ] This being the project title, use an `hx` tag

2021-09-25 00:53 UTC, Mihndim2020 requested changes
## Hi @karam084 , 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![stay-strong-youre-almost-there](https://user-images.githubusercontent.com/65852621/133678845-1b015b27-e9bc-4784-a316-bc699db8237a.jpg)


 # Status: Requires Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-25 00:53 UTC, Mihndim2020 commented on index.html
> +                 <li>Tonic</li>
- [ ] As requested by the previous code reviewer, please make the project titles (e.g. Tonic) are surrounded by an `<hx>` tags.

2021-09-25 00:53 UTC, Mihndim2020 commented on index.html
> +            <div class="resume">Get my resume</div>
- [ ] As requested by the previous code reviewer, this is a button, please kindly fix that.

2021-09-25 00:53 UTC, Mihndim2020 commented on index.html
> +         </div>
- [ ] As requested by the former code reviewer, please implement the changes above. 

***See Design***
![satD](https://user-images.githubusercontent.com/65852621/134752020-231a9dce-444d-438a-ac52-606b854824af.png)
- [ ] For each project, align the content to the left as in the design. 
- [ ] Add complete styles to the about me section specifically the categories (languages, skills, frameworks). Make this section math the given design.
- [OPTIONAL ] Please kindly style the buttons for enabled, hover and pressed states.
- [OPTIONAL] Please make sure your social media icons have uniform size.

2021-09-25 20:59 UTC, carlos-ssh approved these changes
Hi @karam084 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-25 21:15 UTC, merged